<Project>
  <ItemGroup>
    <PackageVersion Include="System.Runtime" Version="4.3.1" />
    <PackageVersion Include="Xamarin.AndroidX.AppCompat" Version="1.7.1.4" />
    <PackageVersion Include="Xamarin.AndroidX.Arch.Core.Runtime" Version="2.2.0.21" />
    <PackageVersion Include="Xamarin.AndroidX.RecyclerView" Version="1.4.0.6" />
    <PackageVersion Include="Xamarin.AndroidX.VectorDrawable" Version="1.2.0.11" />
    <PackageVersion Include="Xamarin.Essentials" Version="1.8.1" />
    <PackageVersion Include="Microsoft.WindowsAppSDK" Version="2.2.0" />
    <PackageVersion Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.2270" />
    <PackageVersion Include="AsyncFixer" Version="2.1.0" />
    <PackageVersion Include="Roslynator.Analyzers" Version="4.15.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="10.0.301" />
    <PackageVersion Include="SonarAnalyzer.CSharp" Version="10.28.0.143324" />
  </ItemGroup>
</Project>