<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-android</TargetFramework>

    <SupportedOSPlatformVersion>23</SupportedOSPlatformVersion>
    
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <!--
      Enable trim analyzers for Android class libraries.
      To learn more, see: https://learn.microsoft.com/dotnet/core/deploying/trimming/prepare-libraries-for-trimming
    -->
    <IsTrimmable>true</IsTrimmable>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <RunAOTAnalysis>true</RunAOTAnalysis>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'!='Debug'">
    <IsPackable>true</IsPackable>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Xamarin.AndroidX.RecyclerView" />
    <PackageReference Include="Xamarin.AndroidX.VectorDrawable" />
  </ItemGroup>
</Project>