<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(_CrossWindowsTargets)</TargetFrameworks>
    <TargetPlatformMinVersion>$(_CrossWindowsPlatformMinVersion)</TargetPlatformMinVersion>
    
    <AssemblyName>Nivaes.TimeLine.WinUI</AssemblyName>
    <RootNamespace>Nivaes.TimeLine.WinUI</RootNamespace>

    <UseWinUI>true</UseWinUI>
    <WinUISDKReferences>false</WinUISDKReferences>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <RunAOTAnalysis>true</RunAOTAnalysis>
  </PropertyGroup>
  <ItemGroup>
    <Content Remove="Images\Icon.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Images\Icon.png" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" />
    <PackageReference Include="Microsoft.WindowsAppSDK" />
  </ItemGroup>

  <PropertyGroup Condition="'$(Configuration)'!='Debug'">
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <PropertyGroup>
    <Description>Time line for WinUI3</Description>
    <PackageId>Nivaes.TimeLine.UIKit</PackageId>
    <PackageTags>xamarin;windows;winui;nivaes</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Images\icon.png" Pack="true" PackagePath="\" />
    <None Include="Docs\Readme.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>