<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(_CrossiOSTargets);$(_CrossMacCatalystTargets);$(_CrossTvOSTargets)</TargetFrameworks>
    
    <AssemblyName>Nivaes.TimeLine.UIKit</AssemblyName>
    <RootNamespace>Nivaes.TimeLine.UIKitLib</RootNamespace>
    
    <Nullable>enable</Nullable>
    <ImplicitUsings>true</ImplicitUsings>

    <!--
      Enable trim analyzers for class libraries.
      To learn more, see: https://learn.microsoft.com/dotnet/core/deploying/trimming/prepare-libraries-for-trimming
    -->
    <IsTrimmable>true</IsTrimmable>
    <RunAOTAnalysis>true</RunAOTAnalysis>
  </PropertyGroup>

  <PropertyGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">
    <SupportedOSPlatformVersion>$(_SupportedOSPlatformiOSVersion)</SupportedOSPlatformVersion>
    <TargetPlatformVersion>$(_TargetPlatformiOSVersion)</TargetPlatformVersion>
  </PropertyGroup>
  <PropertyGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">
    <SupportedOSPlatformVersion>$(_SupportedOSPlatformMacCatalystVersion)</SupportedOSPlatformVersion>
    <TargetPlatformVersion>$(_TargetPlatformMacCatalystVersion)</TargetPlatformVersion>
  </PropertyGroup>
  <PropertyGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tvos'">
    <SupportedOSPlatformVersion>$(_SupportedOSPlatformTvOSVersion)</SupportedOSPlatformVersion>
    <TargetPlatformVersion>$(_TargetPlatformTvOSVersion)</TargetPlatformVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'!='Debug'">
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <PropertyGroup>
    <Description>Time line for iOS and maccatalyst</Description>
    <PackageId>Nivaes.TimeLine.UIKit</PackageId>
    <PackageTags>xamarin;ios;maccatalyst;UIKit;nivaes</PackageTags>
  </PropertyGroup>


  <ItemGroup>
    <None Include="Images\icon.png" Pack="true" PackagePath="\" />
    <None Include="Docs\Readme.md" Pack="true" PackagePath="\" />
  </ItemGroup>


</Project>
