<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFrameworks>net10.0-android;net10.0-ios;net10.0-maccatalyst;net10.0-tvos</TargetFrameworks>
    <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net10.0-windows10.0.19041.0</TargetFrameworks>

    <ImplicitUsings>enable</ImplicitUsings>

    <AssemblyName>Nivaes.TimeLine</AssemblyName>
    <RootNamespace>Nivaes.TimeLine</RootNamespace>

    <OptimizationPreference>Speed</OptimizationPreference>
    <IsTrimmable>true</IsTrimmable>
    <IsAotCompatible>true</IsAotCompatible>
    <RunAOTAnalysis>true</RunAOTAnalysis>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Configuration)'!='Debug'">
    <Title>Nivaes Timeline</Title>
    <Product>TimeLine</Product>
    <Description>Time Line packages for Android, iOS, maccatalyst and WinUI3</Description>
    <Summary>???</Summary>
    <PackageId>Nivaes.TimeLine</PackageId>
    <PackageTags>xamarin;android;iOS;Windows;WinUI;WinUI3;timeline</PackageTags>
    <PackageReleaseNotes>https://www.nivaes.com</PackageReleaseNotes>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <RepositoryUrl>https://github.com/Nivaes/Nivaes.TimeLine</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Images\icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <ApplicationDefinition Remove="**\*.xaml" /> 
  </ItemGroup>

  <ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'macos'">
  </ItemGroup>

  <ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">
    <ProjectReference Include="..\Sources\Nivaes.TimeLine.UIKit\Nivaes.TimeLine.UIKit.csproj" />
  </ItemGroup>

  <ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">
    <ProjectReference Include="..\Sources\Nivaes.TimeLine.UIKit\Nivaes.TimeLine.UIKit.csproj" />
  </ItemGroup>

  <ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tvos'">
    <ProjectReference Include="..\Sources\Nivaes.TimeLine.UIKit\Nivaes.TimeLine.UIKit.csproj" />
  </ItemGroup>

  <ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">
    <ProjectReference Include="..\Sources\Nivaes.TimeLine.Droid\Nivaes.TimeLine.Droid.csproj" />
  </ItemGroup>

  <PropertyGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">
    <Platforms>x64;ARM64</Platforms>
  </PropertyGroup>

  <ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">
    <ProjectReference Include="..\Sources\Nivaes.TimeLine.WinUI\Nivaes.TimeLine.WinUI.csproj" />
  </ItemGroup>

</Project>
