name: CI

on:
  push:
    branches-ignore:
    - 'release/**'
    paths-ignore:
    - '**/*.md'
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
    - '**/*.md'

jobs:
  build-Android:
    runs-on: windows-2019

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core 3.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Setup .NET Core 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        source-url: https://nuget.pkg.github.com/Nivaes/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Install dependencies droid
      run: msbuild /t:restore ./Nivaes.TimeLine.Droid.Sample/

    - name: Build App.Cross.Droid
      run: msbuild ./Nivaes.TimeLine.Droid.Sample/ /property:Configuration=Release

    - name: Install dependencies iOS
      run: msbuild /t:restore ./Nivaes.TimeLine.iOS.Sample/

    - name: Build App.Cross.iOS
      run: msbuild ./Nivaes.TimeLine.iOS.Sample/ /property:Configuration=Release

    - name: Install dependencies WinUI
      run: msbuild /t:restore ./Nivaes.TimeLine.WinUI.UWP.Sample/

    - name: Build App.Cross.WinUI
      run: msbuild ./Nivaes.TimeLine.WinUI.UWP.Sample/ /property:Configuration=Release

    - name: Install dependencies WPF
      run: msbuild /t:restore ./Nivaes.TimeLine.WinUI.WPF.Sample/

    - name: Build App.Cross.WPF
      run: msbuild ./Nivaes.TimeLine.WinUI.WPF.Sample/ /property:Configuration=Release

  build-iOS:
    runs-on: windows-2019

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core 3.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Setup .NET Core 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        source-url: https://nuget.pkg.github.com/Nivaes/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Install dependencies iOS
      run: msbuild /t:restore ./Nivaes.TimeLine.iOS.Sample/

    - name: Build App.Cross.iOS
      run: msbuild ./Nivaes.TimeLine.iOS.Sample/ /property:Configuration=Release

  build-Windows:
    runs-on: windows-2019
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core 3.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Setup .NET Core 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        source-url: https://nuget.pkg.github.com/Nivaes/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Install dependencies WinUI
      run: msbuild /t:restore ./Nivaes.TimeLine.WinUI.UWP.Sample/

    - name: Build App.Cross.WinUI
      run: msbuild ./Nivaes.TimeLine.WinUI.UWP.Sample/ /property:Configuration=Release

    - name: Install dependencies WPF
      run: msbuild /t:restore ./Nivaes.TimeLine.WinUI.WPF.Sample/

    - name: Build App.Cross.WPF
      run: msbuild ./Nivaes.TimeLine.WinUI.WPF.Sample/ /property:Configuration=Release
