name: CI

on:
  push:
    branches-ignore:
    - 'release/**'
    paths-ignore:
    - '**/*.md'
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
    - '**/*.md'

env:
    net_core_version: 8.0.201

jobs:
  build-Android:
    runs-on: windows-2022

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.net_core_version }}
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'microsoft'
        java-version: '17'

    - name: Install workload
      run: |
        dotnet workload install android --ignore-failed-sources --verbosity detailed
        dotnet workload install ios --ignore-failed-sources
        dotnet workload install maccatalyst --ignore-failed-sources

    - name: Restore Dependencies
      run: |
          dotnet restore ./Nivaes.TimeLine/
          dotnet restore ./Nivaes.TimeLine.Droid.Sample/

    - name: Build Nivaes.TimeLine
      run: |
          dotnet build ./Nivaes.TimeLine/ --configuration Release --framework net8.0-android --no-restore

    - name: Build Nivaes.TimeLine.Droid.Sample
      run: |
          dotnet build ./Nivaes.TimeLine.Droid.Sample/ --configuration Release --framework net8.0-android --no-restore

    # https://github.com/jfversluis/MauiGithubActionsSample/blob/main/.github/workflows/dotnet.yml
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-ci-build
        path: |
          ./**/*.*
          # ./**/*.aab
          # ./**/*.apk
          
  # build-iOS:
  #   runs-on: macos-latest

  #   steps:
  #   - name: Dump GitHub context
  #     env:
  #       GITHUB_CONTEXT: ${{ toJson(github) }}
  #     run: echo "$GITHUB_CONTEXT"

  #   - name: Checkout
  #     uses: actions/checkout@v3

  #   - name: Setup .NET Core
  #     uses: actions/setup-dotnet@v3 
  #     with:
  #       dotnet-version: ${{ env.net_core_version }}
  #     env:
  #       NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  #   - name: Install workload
  #     shell: pwsh
  #     run: |
  #       dotnet workload install ios
  #       dotnet workload install macos
  #       dotnet workload install maccatalyst
  #       dotnet workload install tvos

  #   # https://github.com/Apple-Actions/Example-iOS/blob/master/.github/workflows/test.yml
  #   # https://calvium.com/how-to-make-a-p12-file/
  #   # https://www.andreasnesheim.no/setting-up-ci-for-your-net-maui-ios-app-with-github-actions/
  #   # - name: Import Code-Signing Certificates
  #   #   uses: Apple-Actions/import-codesign-certs@v2
  #   #   with:
  #   #     p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
  #   #     p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}

  #   - name: Restore Dependencies
  #     run: dotnet restore ./Nivaes.TimeLine.iOS/

  #   - name: Build App.Cross.iOS
  #     run: |
  #         dotnet build ./Nivaes.TimeLine.iOS/ --configuration Release --framework net8.0-ios --no-restore
  #         dotnet build ./Nivaes.TimeLine.iOS/ --configuration Release --framework net8.0-maccatalyst --no-restore
  #         # /p:ArchiveOnBuild=true /p:EnableAssemblyILStripping=false
    
  #   - name: Upload a Build Artifact
  #     uses: actions/upload-artifact@v4
  #     with:
  #       name: ios-ci-build
  #       path: |
  #           ./**/*.*
  #           # '**/*.ipa'

  build-Windows:
    runs-on: windows-2022
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.net_core_version }}
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    # - name: Setup MSBuild
    #   uses: microsoft/setup-msbuild@v2

    - name: Restore Dependencies
      run: |
          dotnet restore ./Nivaes.TimeLine/
          dotnet restore ./Nivaes.TimeLine.WinUI.Windows.Sample/

    - name: Build Nivaes.TimeLine
      run: |
          dotnet build ./Nivaes.TimeLine/ --configuration Release --framework net8.0-windows10.0.19041.0 --runtime win-x64 --no-restore
          dotnet build ./Nivaes.TimeLine/ --configuration Release --framework net8.0-windows10.0.19041.0 --runtime win-x86 --no-restore
          dotnet build ./Nivaes.TimeLine/ --configuration Release --framework net8.0-windows10.0.19041.0 --runtime win-arm64 --no-restore

    - name: Build Nivaes.TimeLine.Windows.Sample
      run: |
          dotnet build ./Nivaes.TimeLine.WinUI.Windows.Sample/ --configuration Release --framework net8.0-windows10.0.19041.0 --runtime win-x64 --no-restore
          dotnet build ./Nivaes.TimeLine.WinUI.Windows.Sample/ --configuration Release --framework net8.0-windows10.0.19041.0 --runtime win-x86 --no-restore
          dotnet build ./Nivaes.TimeLine.WinUI.Windows.Sample/ --configuration Release --framework net8.0-windows10.0.19041.0 --runtime win-arm64 --no-restore

    #https://github.com/jfversluis/MauiGithubActionsSample/blob/main/.github/workflows/dotnet-windows.yml

    # - name: Build App.Cross.WinUI
    #   run: |
    #       msbuild /m /p:Configuration=Release,Platform=x86 ./Nivaes.TimeLine/
    #       msbuild /m /p:Configuration=Release,Platform=x64 ./Nivaes.TimeLine/
    #       msbuild /m /p:Configuration=Release,Platform=ARM64 ./Nivaes.TimeLine/

    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-ci-build
        path: |
            ./**/*.*
        # ./Nivaes.TimeLine.WinUI.Windows.Sample/bin/Release/net8.0-windows*/**/*.msix

    # - name: Upload Build Artifacts
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: windows-ci-build-apppackages
    #     path: .\**\AppPackages\**\*.*


  build-NuGet:
    runs-on: windows-2022
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.net_core_version }}
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'microsoft'
        java-version: '17'

    - name: Install workload
      run: |
        dotnet workload install android --ignore-failed-sources --verbosity detailed
        dotnet workload install ios --ignore-failed-sources
        dotnet workload install maccatalyst --ignore-failed-sources

    - name: Restore Dependencies
      run: |
          dotnet restore ./Nivaes.TimeLine/

    - name: Build Nivaes.TimeLine
      run: |
          dotnet build ./Nivaes.TimeLine/ --configuration Release --no-restore

    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4
      with:
        name: NuGet-ci-build
        path: |
            ./**/*.*
        # ./Nivaes.TimeLine.WinUI.Windows.Sample/bin/Release/net8.0-windows*/**/*.msix

    # - name: Upload Build Artifacts
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: windows-ci-build-apppackages
    #     path: .\**\AppPackages\**\*.*
