name: CI

on:
  push:
    branches-ignore:
    - 'release/**'
    paths-ignore:
    - '**/*.md'
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
    - '**/*.md'

env:
    net_core_version: 10.0.301

jobs:
  build:
    runs-on: linux-latest

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ env.net_core_version }}
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    # - name: Setup Java
    #   uses: actions/setup-java@v2
    #   with:
    #     distribution: 'microsoft'
    #     java-version: '17'

    - name: Install workload
      run: |
          dotnet workload install android ios, maccatalyst tvos
      # run: |
        # dotnet workload install android --ignore-failed-sources --verbosity detailed
        # dotnet workload install ios --ignore-failed-sources
        # dotnet workload install maccatalyst --ignore-failed-sources
        # dotnet workload install tvos --ignore-failed-sources

    - name: Restore Dependencies
      run: |
          dotnet restore

    - name: Build
      run: |
          dotnet build --configuration Release --no-restore

    - name: Build
      run: |
          dotnet build --configuration Release --no-restore

    - name: Pack
      run: dotnet pack --configuration Release --no-build --verbosity normal --output ./Artifacts/ -p:Version=0.0.1 --no-restore

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: ./Artifacts/
