name: CI

on:
  push:
    branches-ignore:
    - 'release/**'
    paths-ignore:
    - '**/*.md'
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
    - '**/*.md'

jobs:
  build-Android:
    runs-on: windows-2019

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout
      uses: actions/checkout@v2

    #- name: Setup .NET Core 3.1.x
    #  uses: actions/setup-dotnet@v1
    #  with:
    #    dotnet-version: 3.1.x

    #- name: Setup .NET Core 5.0.x
    #  uses: actions/setup-dotnet@v1
    #  with:
    #    dotnet-version: 5.0.x
    #    source-url: https://nuget.pkg.github.com/Nivaes/index.json
    #  env:
    #    NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Setup .NET Core 6.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100-preview.3.21202.5

    #- name: Setup MSBuild
    #  uses: microsoft/setup-msbuild@v1.0.2

    - name: Install Android Workloads
      #env:
      #  ANDROIDWORKLOADS: ${{https://dl.internalx.com/vsts-devdiv/Xamarin.Android/public/net6/4451481/master/05bb8e0eae11ae6a73838b13cf91ee2433169dff/Microsoft.NET.Workload.Android.11.0.200.136.msi}}
      #  MACOSWORKLOADS: ${{https://bosstoragemirror.azureedge.net/wrench/main/f01fde5cd9a7ffffcdc8d241200c35988700fa00/4449408/package/Microsoft.NET.Workload.iOS.14.3.100-ci.main.1171.msi}}
      shell: pwsh
      run: |
        dotnet tool install --global boots
        boots https://dl.internalx.com/vsts-devdiv/Xamarin.Android/public/net6/4624420/6.0.1xx-preview3/7d6cd1cde4182d7db2cfc5d0b55364c972b6d34f/Microsoft.NET.Workload.Android.11.0.200.196.msi


    #- name: Install dependencies
    #  run: |
    #    msbuild /t:restore ./Nivaes.TimeLine.Droid/
    #    msbuild /t:restore ./Nivaes.TimeLine.Droid.Sample/

    #- name: Build App.Cross.Droid
    #  run: msbuild ./Nivaes.TimeLine.Droid/ /property:Configuration=Release

    - name: Build App.Cross.Droid
      run: dotnet build ./Nivaes.TimeLine.Droid/ --configuration Release

  build-iOS:
    runs-on: macos-10.15

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout
      uses: actions/checkout@v2

    #- name: Setup .NET Core 3.1.x
    #  uses: actions/setup-dotnet@v1
    #  with:
    #    dotnet-version: 3.1.x

    #- name: Setup .NET Core 5.0.x
    #  uses: actions/setup-dotnet@v1
    #  with:
    #    dotnet-version: 5.0.x
    #    source-url: https://nuget.pkg.github.com/Nivaes/index.json
    #  env:
    #    NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Setup .NET Core 6.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100-preview.3.21202.5

    - name: Install iOS Workloads
      #env:
      #  ANDROIDWORKLOADS: ${{https://dl.internalx.com/vsts-devdiv/Xamarin.Android/public/net6/4451481/master/05bb8e0eae11ae6a73838b13cf91ee2433169dff/Microsoft.NET.Workload.Android-11.0.200-ci.master.136.pkg}}
      #  MACOSWORKLOADS: ${{https://bosstoragemirror.azureedge.net/wrench/main/f01fde5cd9a7ffffcdc8d241200c35988700fa00/4449408/package/notarized/Microsoft.iOS.Bundle.14.3.100-ci.main.1079.pkg}}
      run: |
        dotnet tool install --global boots
        boots https://dl.internalx.com/vsts-devdiv/Xamarin.Android/public/net6/4624420/6.0.1xx-preview3/7d6cd1cde4182d7db2cfc5d0b55364c972b6d34f/Microsoft.NET.Workload.Android-11.0.200-preview.3.196.pkg
        boots https://bosstoragemirror.azureedge.net/wrench/6.0.1xx-preview3/f68d4d9c2a342daf9eaad364ccbe252e009d3901/4623693/package/notarized/Microsoft.iOS.Bundle.14.4.100-preview.3.1326.pkg
        boots https://bosstoragemirror.azureedge.net/wrench/6.0.1xx-preview3/f68d4d9c2a342daf9eaad364ccbe252e009d3901/4623693/package/notarized/Microsoft.macOS.Bundle.11.1.100-preview.3.1379.pkg
        boots https://bosstoragemirror.azureedge.net/wrench/6.0.1xx-preview3/f68d4d9c2a342daf9eaad364ccbe252e009d3901/4623693/package/notarized/Microsoft.MacCatalyst.Bundle.14.3.100-preview.3.471.pkg

    - name: Install Xcode 12.4
      run: sudo xcode-select -s /Applications/Xcode_12.4.app

    - name: configure vsmac xcode
      run: |
        set -x
        mkdir -p ~/Library/Preferences/Xamarin
        rm -f ~/Library/Preferences/Xamarin/Settings.plist
        /usr/libexec/PlistBuddy -c "add :AppleSdkRoot string $(dirname $(dirname $(xcode-select -p)))" ~/Library/Preferences/Xamarin/Settings.plist || true
        cat ~/Library/Preferences/Xamarin/Settings.plist || true


    #- name: Setup MSBuild
    #  uses: microsoft/setup-msbuild@v1.0.2

    #- name: Install dependencies
    #  run: |
    #    msbuild /t:restore ./Nivaes.TimeLine.iOS/
    #    msbuild /t:restore ./Nivaes.TimeLine.iOS.Sample/

    #- name: Build App.Cross.iOS
    #  run: msbuild ./Nivaes.TimeLine.iOS/ /property:Configuration=Release

    #- name: Build App.Cross.iOS
    #  run: dotnet build ./Nivaes.TimeLine.Droid/ --configuration Release

  build-Windows:
    runs-on: windows-2019
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout
      uses: actions/checkout@v2

    #- name: Setup .NET Core 3.1.x
    #  uses: actions/setup-dotnet@v1
    #  with:
    #    dotnet-version: 3.1.x

    - name: Setup .NET Core 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        source-url: https://nuget.pkg.github.com/Nivaes/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Setup .NET Core 6.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100-preview.1.21103.13

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Install dependencies
      run: |
        msbuild /t:restore ./Nivaes.TimeLine.WinUI/
        msbuild /t:restore ./Nivaes.TimeLine.WinUI.Windows.Sample/
        msbuild /t:restore ./Nivaes.TimeLine.WinUI.WPF.Windows.Sample/

    - name: Build App.Cross.WinUI
      run: msbuild ./Nivaes.TimeLine.WinUI/ /property:Configuration=Release

    #- name: Build Nivaes.TimeLine.WinUI.Windows.Sample
    #  run: msbuild ./Nivaes.TimeLine.WinUI.Windows.Sample/ /property:Configuration=Release

    #- name: Build Nivaes.TimeLine.WinUI.WPF.Windows.Sample
    #  run: msbuild ./Nivaes.TimeLine.WinUI.WPF.Windows.Sample/ /property:Configuration=Release
