name: Publish Release

on:
  release:
    #types:[edited]
    #types: [published]
    types:
      - released
      - prereleased
    #types: [deleted]

jobs:
  publish_release:
    runs-on: ubuntu-22.04

    steps:

    - name: Get Version
      uses: nivaes/version-run-number@develop
      id: version_run_number

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: release
      if: github.event.action == 'released'
      run: echo Release

    - name: prereleased
      if: github.event.action == 'prereleased'
      run: echo Prereleased

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          8.0.x

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'microsoft'
        java-version: '17'

    - name: Install workload
      run: |
        dotnet workload install android --ignore-failed-sources --verbosity detailed
        dotnet workload install ios --ignore-failed-sources
        dotnet workload install maccatalyst --ignore-failed-sources
          
    - name: Checkout
      uses: actions/checkout@v3

    - name: Restore Dependencies
      run: |
          dotnet restore ./Nivaes.TimeLine/

    - name: Build
      run: dotnet build ./Nivaes.TimeLine/ --configuration Release -p:Version=${{ steps.version_run_number.outputs.version }} --no-restore

    - name: Test
      run: dotnet test ./Nivaes.TimeLine/ --configuration Release --no-build --verbosity normal --no-restore

    - name: Pack
      run: dotnet pack ./Nivaes.TimeLine/ --configuration Release --no-build --verbosity normal --output ./Artifacts/ -p:Version=${{ steps.version_run_number.outputs.version }} --no-restore

    #- name: Download Release Asset
    #  env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #  uses: nivaes/download-release-assets@master

    - name: Publish packages
      run: dotnet nuget push ./**/*.nupkg --skip-duplicate --source nuget.org --api-key ${{secrets.NIVAES_NUGET_TOKEN}}
